name: Template CI Infra Checks

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - bin/**
      - infra/**
      - template-only-bin/**
      - template-only-test/**
      - .github/workflows/template-only-ci-infra.yml
      - template-only-app/Dockerfile
  workflow_dispatch:

concurrency: platform-template-only-ci-infra

jobs:
  # lint:
  #   name: Lint template scripts
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Shellcheck
  #       run: make -f template-only.mak lint-template-scripts

  test:
    name: Infra Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout template-infra repo
        uses: actions/checkout@v4
        with:
          path: template-infra

      - name: Set up Terraform
        uses: ./template-infra/.github/actions/setup-terraform
        with:
          version-file: ./template-infra/.terraform-version

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./template-infra/template-only-test/go.mod

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install nava-platform CLI
        run: pipx install --python "$(which python)" git+https://github.com/navapbc/platform-cli

      # TODO: configure azure
      # - uses: azure/login@v2
      #   with:
      #     tenant-id: ${{ env.ARM_TENANT_ID }}
      #     subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
      #     client-id: ${{ env.ARM_CLIENT_ID }}
      #
      # AWS setup for reference
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-region: us-east-1

      #     # Use access key credentials for the template infra test workflow
      #     # instead of using GitHub OIDC because only one GitHub OIDC provider
      #     # can be added to the Platform account, and we want to create a
      #     # GitHub OIDC provider as part of the template test.
      #     # (see https://docs.aws.amazon.com/cli/latest/reference/iam/create-open-id-connect-provider.html)
      #     #
      #     # For this test, use PlatformTestUser20220726 credentials
      #     aws-access-key-id: ${{ secrets.TESTER_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.TESTER_AWS_SECRET_ACCESS_KEY }}

      - name: Run infra tests
        working-directory: project-dir
        run: ./template-only-bin/test-infra . ../template-infra
        env:
          # GitHub token needed for GitHub CLI which is used during tests to check GitHub Actions auth
          GH_TOKEN: ${{ secrets.PLATFORM_TESTER_GITHUB_TOKEN }}
          IMAGE_TAG: ${{ github.sha }}
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
